### PR TITLE
Working on usability with .py scripts

### PR DESCRIPTION
**Pull request by Rohitrajak1807**
rename writer_func to writer_wrapper
move the decorator outside the Writer class
file_handle is an instance member
close_file_handle is an instance method
file_handle initialized in __init__, __get_file_handle not needed anymore

### CODE REVIEW

**Comment by Rohitrajak1807** [comment]
@PrasanthChettri please check and give your views

**Comment by PrasanthChettri** [comment]
writer_func seems awkward outside, I think it would be better if it is encapsulated under the Writer class probably as a static method.

**Comment by Rohitrajak1807** [comment]
> @Rohitrajak1807 ~~writer_func~~ writer wrapper seems awkward outside, I think it would be better if it is encapsulated under the Writer class probably as a static method. 

Yeah, thats agreeable. Let me see what can be done

**Review by PrasanthChettri — COMMENTED** [review]
We are opening the file in the initializer and closing it after printing, the scope seems inconsistent, we should probably revert back to what we were doing .i.e. the limiting scope to one writer function or make it so that the file closes at a destructor

**Comment by Rohitrajak1807** [comment]
> @Rohitrajak1807 We are opening the file in the initializer and closing it after ~~printing~~ the writer function is being called, the scope seems inconsistent, we should probably revert back to what we were doing .i.e. the limiting scope to one writer function or make it so that the file closes at a destructor 

- [ ] According to RAII, the current decorator is badly written. I think moving it to the destructor is better as it'll clean up the code

**Comment by PrasanthChettri** [comment]
@Rohitrajak1807 Yeah that sounds good

**Comment by Rohitrajak1807** [comment]
> @Rohitrajak1807 Yeah that sounds good

Check now

**Comment by PrasanthChettri** [comment]
LGTM

**Comment by Rohitrajak1807** [comment]
@avaish1409, @PrasanthChettri, please review and merge if it's fine

**Comment by PrasanthChettri** [comment]
LGTM 👍

**Review by avaish1409 — APPROVED** [review]

**Pull request merged**
