### PR TITLE
Added precise version compatibility

### PR DESCRIPTION
**Pull request by PrasanthChettri**
Package does not support python3.6 or below, configuring the setup.py with python version3.7 or more

### CODE REVIEW

**Comment by avaish1409** [comment]
As per the dependencies, the package should work fine with py35 or above. Please let me know if you checked it using tox or some other tool.

**Comment by Rohitrajak1807** [comment]
@avaish1409 python 3.6 is needed because of string templates and possibly some other features. So I do agree that minimum version should be 3.6

**Comment by PrasanthChettri** [comment]
image

It did not work on my local python3.6 install running linux, it seems to work 3.7 onwards, you guys can check on your machines if it is an issue on my side

**Comment by Rohitrajak1807** [comment]
It says can't find __main__ so it may not be a compatibility issue.

**Comment by PrasanthChettri** [comment]
Scratch that it works, just not on a local package, will revise the version in the config

**Pull request merged**
